[node-red-contrib-binpacking]  adapt bin packing algorithm for no-stackable packages
yoctu/node-red-contrib-binpacking pull request #18
Opened 2022-01-17 10:57 UTC by mrazafindrazaka

Adapted algorithm for no-stackable packages and test with jest + supertest

2022-01-17 11:05 UTC, acacopardo commented
Can you remove package.json.lock please ?
for a library is not recommended.

2022-01-17 11:05 UTC, acacopardo commented on package.json
> -    "test": "npm run lint",
test commande should run all test lint + jest.
Can you di a specific commande for jest test and modify test commande to run jest and test npm commande please ?

2022-01-17 13:10 UTC, gbo-redspher approved these changes
Code-wise it seems fine for me, for the business logic part I'd rather wait for @fanshan or @glickel review

2022-01-18 08:48 UTC, glickel requested changes

2022-01-18 08:48 UTC, glickel commented on index.js
> +          if (!Object.prototype.hasOwnProperty.call(msg.packages[pkg], 'stackable')) {
```suggestion
          if (typeof msg.packages[pkg].stackable === 'undefined') {
```

2022-01-18 08:48 UTC, glickel commented on index.js
> +          if (!Object.prototype.hasOwnProperty.call(msg.packages[pkg], 'stackable')) {
Easier to read

2022-01-18 08:48 UTC, glickel commented on index.js
> +                    msg.packages[pkg].weight, msg.packages[pkg].allowedRotation),
```suggestion
                  item: new Item(
                    msg.packages[pkg].name + ' ' + q, msg.packages[pkg].width,
                    msg.packages[pkg].height, msg.packages[pkg].length,
                    msg.packages[pkg].weight, msg.packages[pkg].allowedRotation
                  ),
```

Easier to read

2022-01-18 09:21 UTC, glickel approved these changes

2022-01-18 09:24 UTC, acacopardo approved these changes

2022-01-18 09:24 UTC, acacopardo commented on package.json
>    "version": "1.2.3"
```suggestion
  "version": "1.3.0"
```

2022-01-18 09:30 UTC, merged